# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    replaces = [('tracts', '0001_initial'), ('tracts', '0002_auto_20161009_0136'), ('tracts', '0003_remove_tract_gid'), ('tracts', '0004_auto_20161011_0504'), ('tracts', '0005_auto_20161011_0539')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('short_legal', models.CharField(max_length=100)),
                ('full_legal', models.TextField()),
                ('situs_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tracts',
            },
        ),
    ]
