# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracts',
            new_name='Tract',
        ),
    ]
