# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracts', '0002_auto_20161009_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tract',
            name='gid',
        ),
    ]
