# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracts', '0004_auto_20161011_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='tract',
            name='acreage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tract',
            name='full_legal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tract',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
