# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracts', '0004_auto_20161011_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tract',
            name='full_legal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tract',
            name='owner',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
