# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunsheetRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('SEC 4 BLK 392S', 'Section 4 Block 39 T2S'), ('CAR', 'cars')], max_length=100)),
            ],
        ),
    ]
