# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_document_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunRequestDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=4)),
                ('page', models.CharField(max_length=4)),
                ('rec_type', models.CharField(max_length=4)),
                ('year', models.CharField(max_length=4)),
                ('inst_num', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2016-09-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='runrequestdocs',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Document'),
        ),
    ]
