# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20160927_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunReq',
            fields=[
                ('pull_id', models.AutoField(primary_key=True, serialize=False)),
                ('landman', models.IntegerField()),
                ('document_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='runrequestdocs',
            old_name='request_id',
            new_name='pull_id',
        ),
    ]
