# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20160927_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runreq',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
